// The 197 quizzable sovereign countries — every one recognized widely enough to be a fair quiz
// question, not just the well-known ones (down to Tuvalu, the world's 4th-smallest country by
// area). `id` matches the join key the client's map geometry uses (ISO 3166-1 numeric codes,
// from the same public-domain Natural Earth-derived boundary data — see
// packages/client/src/data/). A handful of ids are synthetic slugs ('kosovo') for the few
// entries that dataset ships with no official numeric code at all.
//
// Deliberately excluded from this list (still rendered on the map as background, just never
// asked about): colonial/overseas territories and dependencies (Puerto Rico, Bermuda, French
// Polynesia, Hong Kong, Greenland, Gibraltar, ...), Antarctica, uninhabited/disputed reefs and
// shoals, and a small number of disputed/unrecognized regions (Northern Cyprus, Somaliland,
// Western Sahara) where taking a position isn't this app's job — same "lean on the neutral,
// widely-used convention rather than making an editorial call" approach discussed for the map
// generally. Taiwan, Kosovo, Vatican City, and Palestine ARE included as quizzable, matching
// how they're already treated as distinct entities in the underlying boundary dataset and how
// most general-purpose geography references/quizzes treat them.
//
// `aliases` are additional accepted answers for "type it" mode — common alternate names,
// abbreviations, or older names still in everyday use (see matching.ts for how these get
// matched leniently, e.g. minor typos).
//
// `capitals`/`languages`/`flagEmoji` were bulk-generated from the `world-countries` npm
// package (MIT-licensed, itself sourced from Wikipedia + restcountries.com), matched by ISO
// numeric code (Kosovo matched by cca2 'XK' instead, since it has no ISO numeric code — see the
// `id` note above). Deliberately NOT population: that package doesn't carry it, and hand-typing
// or hand-checking population figures for 197 countries risked shipping stale/wrong numbers for
// something that's supposed to be a quick reference, not a research source — left off rather
// than guessed. `world-countries` was a one-time dev-time data source, not a runtime dependency
// — it's already been uninstalled; regenerate by reinstalling it temporarily if this data ever
// needs refreshing.
import { CountryDef } from './types.js';

export const COUNTRIES: CountryDef[] = [
  { id: '004', name: "Afghanistan", continent: 'Asia', capitals: ["Kabul"], languages: ["Dari", "Pashto", "Turkmen"], flagEmoji: "🇦🇫" },
  { id: '008', name: "Albania", continent: 'Europe', capitals: ["Tirana"], languages: ["Albanian"], flagEmoji: "🇦🇱" },
  { id: '012', name: "Algeria", continent: 'Africa', capitals: ["Algiers"], languages: ["Arabic"], flagEmoji: "🇩🇿" },
  { id: '020', name: "Andorra", continent: 'Europe', capitals: ["Andorra la Vella"], languages: ["Catalan"], flagEmoji: "🇦🇩" },
  { id: '024', name: "Angola", continent: 'Africa', capitals: ["Luanda"], languages: ["Portuguese"], flagEmoji: "🇦🇴" },
  { id: '028', name: "Antigua and Barbuda", continent: 'North America', capitals: ["Saint John's"], languages: ["English"], flagEmoji: "🇦🇬" },
  { id: '032', name: "Argentina", continent: 'South America', capitals: ["Buenos Aires"], languages: ["Guaraní", "Spanish"], flagEmoji: "🇦🇷" },
  { id: '051', name: "Armenia", continent: 'Asia', capitals: ["Yerevan"], languages: ["Armenian"], flagEmoji: "🇦🇲" },
  { id: '036', name: "Australia", continent: 'Oceania', capitals: ["Canberra"], languages: ["English"], flagEmoji: "🇦🇺" },
  { id: '040', name: "Austria", continent: 'Europe', capitals: ["Vienna"], languages: ["Austro-Bavarian German"], flagEmoji: "🇦🇹" },
  { id: '031', name: "Azerbaijan", continent: 'Asia', capitals: ["Baku"], languages: ["Azerbaijani", "Russian"], flagEmoji: "🇦🇿" },
  { id: '044', name: "Bahamas", continent: 'North America', aliases: ["The Bahamas"], capitals: ["Nassau"], languages: ["English"], flagEmoji: "🇧🇸" },
  { id: '048', name: "Bahrain", continent: 'Asia', capitals: ["Manama"], languages: ["Arabic"], flagEmoji: "🇧🇭" },
  { id: '050', name: "Bangladesh", continent: 'Asia', capitals: ["Dhaka"], languages: ["Bengali"], flagEmoji: "🇧🇩" },
  { id: '052', name: "Barbados", continent: 'North America', capitals: ["Bridgetown"], languages: ["English"], flagEmoji: "🇧🇧" },
  { id: '112', name: "Belarus", continent: 'Europe', capitals: ["Minsk"], languages: ["Belarusian", "Russian"], flagEmoji: "🇧🇾" },
  { id: '056', name: "Belgium", continent: 'Europe', capitals: ["Brussels"], languages: ["German", "French", "Dutch"], flagEmoji: "🇧🇪" },
  { id: '084', name: "Belize", continent: 'North America', capitals: ["Belmopan"], languages: ["Belizean Creole", "English", "Spanish"], flagEmoji: "🇧🇿" },
  { id: '204', name: "Benin", continent: 'Africa', capitals: ["Porto-Novo"], languages: ["French"], flagEmoji: "🇧🇯" },
  { id: '064', name: "Bhutan", continent: 'Asia', capitals: ["Thimphu"], languages: ["Dzongkha"], flagEmoji: "🇧🇹" },
  { id: '068', name: "Bolivia", continent: 'South America', capitals: ["Sucre"], languages: ["Aymara", "Guaraní", "Quechua", "Spanish"], flagEmoji: "🇧🇴" },
  { id: '070', name: "Bosnia and Herzegovina", continent: 'Europe', aliases: ["Bosnia"], capitals: ["Sarajevo"], languages: ["Bosnian", "Croatian", "Serbian"], flagEmoji: "🇧🇦" },
  { id: '072', name: "Botswana", continent: 'Africa', capitals: ["Gaborone"], languages: ["English", "Tswana"], flagEmoji: "🇧🇼" },
  { id: '076', name: "Brazil", continent: 'South America', capitals: ["Brasília"], languages: ["Portuguese"], flagEmoji: "🇧🇷" },
  { id: '096', name: "Brunei", continent: 'Asia', capitals: ["Bandar Seri Begawan"], languages: ["Malay"], flagEmoji: "🇧🇳" },
  { id: '100', name: "Bulgaria", continent: 'Europe', capitals: ["Sofia"], languages: ["Bulgarian"], flagEmoji: "🇧🇬" },
  { id: '854', name: "Burkina Faso", continent: 'Africa', capitals: ["Ouagadougou"], languages: ["French"], flagEmoji: "🇧🇫" },
  { id: '108', name: "Burundi", continent: 'Africa', capitals: ["Gitega"], languages: ["French", "Kirundi"], flagEmoji: "🇧🇮" },
  { id: '132', name: "Cabo Verde", continent: 'Africa', aliases: ["Cape Verde"], capitals: ["Praia"], languages: ["Portuguese"], flagEmoji: "🇨🇻" },
  { id: '116', name: "Cambodia", continent: 'Asia', capitals: ["Phnom Penh"], languages: ["Khmer"], flagEmoji: "🇰🇭" },
  { id: '120', name: "Cameroon", continent: 'Africa', capitals: ["Yaoundé"], languages: ["English", "French"], flagEmoji: "🇨🇲" },
  { id: '124', name: "Canada", continent: 'North America', capitals: ["Ottawa"], languages: ["English", "French"], flagEmoji: "🇨🇦" },
  { id: '140', name: "Central African Republic", continent: 'Africa', aliases: ["CAR"], capitals: ["Bangui"], languages: ["French", "Sango"], flagEmoji: "🇨🇫" },
  { id: '148', name: "Chad", continent: 'Africa', capitals: ["N'Djamena"], languages: ["Arabic", "French"], flagEmoji: "🇹🇩" },
  { id: '152', name: "Chile", continent: 'South America', capitals: ["Santiago"], languages: ["Spanish"], flagEmoji: "🇨🇱" },
  { id: '156', name: "China", continent: 'Asia', capitals: ["Beijing"], languages: ["Chinese"], flagEmoji: "🇨🇳" },
  { id: '170', name: "Colombia", continent: 'South America', capitals: ["Bogotá"], languages: ["Spanish"], flagEmoji: "🇨🇴" },
  { id: '174', name: "Comoros", continent: 'Africa', capitals: ["Moroni"], languages: ["Arabic", "French", "Comorian"], flagEmoji: "🇰🇲" },
  { id: '188', name: "Costa Rica", continent: 'North America', capitals: ["San José"], languages: ["Spanish"], flagEmoji: "🇨🇷" },
  { id: '384', name: "Côte d'Ivoire", continent: 'Africa', aliases: ["Ivory Coast"], capitals: ["Yamoussoukro"], languages: ["French"], flagEmoji: "🇨🇮" },
  { id: '191', name: "Croatia", continent: 'Europe', capitals: ["Zagreb"], languages: ["Croatian"], flagEmoji: "🇭🇷" },
  { id: '192', name: "Cuba", continent: 'North America', capitals: ["Havana"], languages: ["Spanish"], flagEmoji: "🇨🇺" },
  { id: '196', name: "Cyprus", continent: 'Europe', capitals: ["Nicosia"], languages: ["Greek", "Turkish"], flagEmoji: "🇨🇾" },
  { id: '203', name: "Czechia", continent: 'Europe', aliases: ["Czech Republic"], capitals: ["Prague"], languages: ["Czech", "Slovak"], flagEmoji: "🇨🇿" },
  { id: '180', name: "Democratic Republic of the Congo", continent: 'Africa', aliases: ["DR Congo", "DRC", "Congo-Kinshasa", "Zaire"], capitals: ["Kinshasa"], languages: ["French", "Kikongo", "Lingala", "Tshiluba", "Swahili"], flagEmoji: "🇨🇩" },
  { id: '208', name: "Denmark", continent: 'Europe', capitals: ["Copenhagen"], languages: ["Danish"], flagEmoji: "🇩🇰" },
  { id: '262', name: "Djibouti", continent: 'Africa', capitals: ["Djibouti"], languages: ["Arabic", "French"], flagEmoji: "🇩🇯" },
  { id: '212', name: "Dominica", continent: 'North America', capitals: ["Roseau"], languages: ["English"], flagEmoji: "🇩🇲" },
  { id: '214', name: "Dominican Republic", continent: 'North America', capitals: ["Santo Domingo"], languages: ["Spanish"], flagEmoji: "🇩🇴" },
  { id: '218', name: "Ecuador", continent: 'South America', capitals: ["Quito"], languages: ["Spanish"], flagEmoji: "🇪🇨" },
  { id: '818', name: "Egypt", continent: 'Africa', capitals: ["Cairo"], languages: ["Arabic"], flagEmoji: "🇪🇬" },
  { id: '222', name: "El Salvador", continent: 'North America', capitals: ["San Salvador"], languages: ["Spanish"], flagEmoji: "🇸🇻" },
  { id: '226', name: "Equatorial Guinea", continent: 'Africa', capitals: ["Malabo"], languages: ["French", "Portuguese", "Spanish"], flagEmoji: "🇬🇶" },
  { id: '232', name: "Eritrea", continent: 'Africa', capitals: ["Asmara"], languages: ["Arabic", "English", "Tigrinya"], flagEmoji: "🇪🇷" },
  { id: '233', name: "Estonia", continent: 'Europe', capitals: ["Tallinn"], languages: ["Estonian"], flagEmoji: "🇪🇪" },
  { id: '748', name: "Eswatini", continent: 'Africa', aliases: ["Swaziland", "eSwatini"], capitals: ["Lobamba"], languages: ["English", "Swazi"], flagEmoji: "🇸🇿" },
  { id: '231', name: "Ethiopia", continent: 'Africa', capitals: ["Addis Ababa"], languages: ["Amharic"], flagEmoji: "🇪🇹" },
  { id: '242', name: "Fiji", continent: 'Oceania', capitals: ["Suva"], languages: ["English", "Fijian", "Fiji Hindi"], flagEmoji: "🇫🇯" },
  { id: '246', name: "Finland", continent: 'Europe', capitals: ["Helsinki"], languages: ["Finnish", "Swedish"], flagEmoji: "🇫🇮" },
  { id: '250', name: "France", continent: 'Europe', capitals: ["Paris"], languages: ["French"], flagEmoji: "🇫🇷" },
  { id: '266', name: "Gabon", continent: 'Africa', capitals: ["Libreville"], languages: ["French"], flagEmoji: "🇬🇦" },
  { id: '270', name: "Gambia", continent: 'Africa', aliases: ["The Gambia"], capitals: ["Banjul"], languages: ["English"], flagEmoji: "🇬🇲" },
  { id: '268', name: "Georgia", continent: 'Asia', capitals: ["Tbilisi"], languages: ["Georgian"], flagEmoji: "🇬🇪" },
  { id: '276', name: "Germany", continent: 'Europe', capitals: ["Berlin"], languages: ["German"], flagEmoji: "🇩🇪" },
  { id: '288', name: "Ghana", continent: 'Africa', capitals: ["Accra"], languages: ["English"], flagEmoji: "🇬🇭" },
  { id: '300', name: "Greece", continent: 'Europe', capitals: ["Athens"], languages: ["Greek"], flagEmoji: "🇬🇷" },
  { id: '308', name: "Grenada", continent: 'North America', capitals: ["St. George's"], languages: ["English"], flagEmoji: "🇬🇩" },
  { id: '320', name: "Guatemala", continent: 'North America', capitals: ["Guatemala City"], languages: ["Spanish"], flagEmoji: "🇬🇹" },
  { id: '324', name: "Guinea", continent: 'Africa', capitals: ["Conakry"], languages: ["French"], flagEmoji: "🇬🇳" },
  { id: '624', name: "Guinea-Bissau", continent: 'Africa', capitals: ["Bissau"], languages: ["Portuguese", "Upper Guinea Creole"], flagEmoji: "🇬🇼" },
  { id: '328', name: "Guyana", continent: 'South America', capitals: ["Georgetown"], languages: ["English"], flagEmoji: "🇬🇾" },
  { id: '332', name: "Haiti", continent: 'North America', capitals: ["Port-au-Prince"], languages: ["French", "Haitian Creole"], flagEmoji: "🇭🇹" },
  { id: '340', name: "Honduras", continent: 'North America', capitals: ["Tegucigalpa"], languages: ["Spanish"], flagEmoji: "🇭🇳" },
  { id: '348', name: "Hungary", continent: 'Europe', capitals: ["Budapest"], languages: ["Hungarian"], flagEmoji: "🇭🇺" },
  { id: '352', name: "Iceland", continent: 'Europe', capitals: ["Reykjavik"], languages: ["Icelandic"], flagEmoji: "🇮🇸" },
  { id: '356', name: "India", continent: 'Asia', capitals: ["New Delhi"], languages: ["English", "Hindi", "Tamil"], flagEmoji: "🇮🇳" },
  { id: '360', name: "Indonesia", continent: 'Asia', capitals: ["Jakarta"], languages: ["Indonesian"], flagEmoji: "🇮🇩" },
  { id: '364', name: "Iran", continent: 'Asia', capitals: ["Tehran"], languages: ["Persian (Farsi)"], flagEmoji: "🇮🇷" },
  { id: '368', name: "Iraq", continent: 'Asia', capitals: ["Baghdad"], languages: ["Arabic", "Aramaic", "Sorani"], flagEmoji: "🇮🇶" },
  { id: '372', name: "Ireland", continent: 'Europe', capitals: ["Dublin"], languages: ["English", "Irish"], flagEmoji: "🇮🇪" },
  { id: '376', name: "Israel", continent: 'Asia', capitals: ["Jerusalem"], languages: ["Arabic", "Hebrew"], flagEmoji: "🇮🇱" },
  { id: '380', name: "Italy", continent: 'Europe', capitals: ["Rome"], languages: ["Italian"], flagEmoji: "🇮🇹" },
  { id: '388', name: "Jamaica", continent: 'North America', capitals: ["Kingston"], languages: ["English", "Jamaican Patois"], flagEmoji: "🇯🇲" },
  { id: '392', name: "Japan", continent: 'Asia', capitals: ["Tokyo"], languages: ["Japanese"], flagEmoji: "🇯🇵" },
  { id: '400', name: "Jordan", continent: 'Asia', capitals: ["Amman"], languages: ["Arabic"], flagEmoji: "🇯🇴" },
  { id: '398', name: "Kazakhstan", continent: 'Asia', capitals: ["Astana"], languages: ["Kazakh", "Russian"], flagEmoji: "🇰🇿" },
  { id: '404', name: "Kenya", continent: 'Africa', capitals: ["Nairobi"], languages: ["English", "Swahili"], flagEmoji: "🇰🇪" },
  { id: '296', name: "Kiribati", continent: 'Oceania', capitals: ["South Tarawa"], languages: ["English", "Gilbertese"], flagEmoji: "🇰🇮" },
  { id: 'kosovo', name: "Kosovo", continent: 'Europe', capitals: ["Pristina"], languages: ["Albanian", "Serbian"], flagEmoji: "🇽🇰" },
  { id: '414', name: "Kuwait", continent: 'Asia', capitals: ["Kuwait City"], languages: ["Arabic"], flagEmoji: "🇰🇼" },
  { id: '417', name: "Kyrgyzstan", continent: 'Asia', capitals: ["Bishkek"], languages: ["Kyrgyz", "Russian"], flagEmoji: "🇰🇬" },
  { id: '418', name: "Laos", continent: 'Asia', capitals: ["Vientiane"], languages: ["Lao"], flagEmoji: "🇱🇦" },
  { id: '428', name: "Latvia", continent: 'Europe', capitals: ["Riga"], languages: ["Latvian"], flagEmoji: "🇱🇻" },
  { id: '422', name: "Lebanon", continent: 'Asia', capitals: ["Beirut"], languages: ["Arabic", "French"], flagEmoji: "🇱🇧" },
  { id: '426', name: "Lesotho", continent: 'Africa', capitals: ["Maseru"], languages: ["English", "Sotho"], flagEmoji: "🇱🇸" },
  { id: '430', name: "Liberia", continent: 'Africa', capitals: ["Monrovia"], languages: ["English"], flagEmoji: "🇱🇷" },
  { id: '434', name: "Libya", continent: 'Africa', capitals: ["Tripoli"], languages: ["Arabic"], flagEmoji: "🇱🇾" },
  { id: '438', name: "Liechtenstein", continent: 'Europe', capitals: ["Vaduz"], languages: ["German"], flagEmoji: "🇱🇮" },
  { id: '440', name: "Lithuania", continent: 'Europe', capitals: ["Vilnius"], languages: ["Lithuanian"], flagEmoji: "🇱🇹" },
  { id: '442', name: "Luxembourg", continent: 'Europe', capitals: ["Luxembourg"], languages: ["German", "French", "Luxembourgish"], flagEmoji: "🇱🇺" },
  { id: '450', name: "Madagascar", continent: 'Africa', capitals: ["Antananarivo"], languages: ["French", "Malagasy"], flagEmoji: "🇲🇬" },
  { id: '454', name: "Malawi", continent: 'Africa', capitals: ["Lilongwe"], languages: ["English", "Chewa"], flagEmoji: "🇲🇼" },
  { id: '458', name: "Malaysia", continent: 'Asia', capitals: ["Kuala Lumpur"], languages: ["English", "Malay"], flagEmoji: "🇲🇾" },
  { id: '462', name: "Maldives", continent: 'Asia', capitals: ["Malé"], languages: ["Maldivian"], flagEmoji: "🇲🇻" },
  { id: '466', name: "Mali", continent: 'Africa', capitals: ["Bamako"], languages: ["French"], flagEmoji: "🇲🇱" },
  { id: '470', name: "Malta", continent: 'Europe', capitals: ["Valletta"], languages: ["English", "Maltese"], flagEmoji: "🇲🇹" },
  { id: '584', name: "Marshall Islands", continent: 'Oceania', capitals: ["Majuro"], languages: ["English", "Marshallese"], flagEmoji: "🇲🇭" },
  { id: '478', name: "Mauritania", continent: 'Africa', capitals: ["Nouakchott"], languages: ["Arabic"], flagEmoji: "🇲🇷" },
  { id: '480', name: "Mauritius", continent: 'Africa', capitals: ["Port Louis"], languages: ["English", "French", "Mauritian Creole"], flagEmoji: "🇲🇺" },
  { id: '484', name: "Mexico", continent: 'North America', capitals: ["Mexico City"], languages: ["Spanish"], flagEmoji: "🇲🇽" },
  { id: '583', name: "Micronesia", continent: 'Oceania', aliases: ["Federated States of Micronesia"], capitals: ["Palikir"], languages: ["English"], flagEmoji: "🇫🇲" },
  { id: '498', name: "Moldova", continent: 'Europe', capitals: ["Chișinău"], languages: ["Moldavian"], flagEmoji: "🇲🇩" },
  { id: '492', name: "Monaco", continent: 'Europe', capitals: ["Monaco"], languages: ["French"], flagEmoji: "🇲🇨" },
  { id: '496', name: "Mongolia", continent: 'Asia', capitals: ["Ulan Bator"], languages: ["Mongolian"], flagEmoji: "🇲🇳" },
  { id: '499', name: "Montenegro", continent: 'Europe', capitals: ["Podgorica"], languages: ["Montenegrin"], flagEmoji: "🇲🇪" },
  { id: '504', name: "Morocco", continent: 'Africa', capitals: ["Rabat"], languages: ["Arabic", "Berber"], flagEmoji: "🇲🇦" },
  { id: '508', name: "Mozambique", continent: 'Africa', capitals: ["Maputo"], languages: ["Portuguese"], flagEmoji: "🇲🇿" },
  { id: '104', name: "Myanmar", continent: 'Asia', aliases: ["Burma"], capitals: ["Naypyidaw"], languages: ["Burmese"], flagEmoji: "🇲🇲" },
  { id: '516', name: "Namibia", continent: 'Africa', capitals: ["Windhoek"], languages: ["Afrikaans", "German", "English", "Herero", "Khoekhoe", "Kwangali", "Lozi", "Ndonga", "Tswana"], flagEmoji: "🇳🇦" },
  { id: '520', name: "Nauru", continent: 'Oceania', capitals: ["Yaren"], languages: ["English", "Nauru"], flagEmoji: "🇳🇷" },
  { id: '524', name: "Nepal", continent: 'Asia', capitals: ["Kathmandu"], languages: ["Nepali"], flagEmoji: "🇳🇵" },
  { id: '528', name: "Netherlands", continent: 'Europe', aliases: ["Holland"], capitals: ["Amsterdam"], languages: ["Dutch"], flagEmoji: "🇳🇱" },
  { id: '554', name: "New Zealand", continent: 'Oceania', capitals: ["Wellington"], languages: ["English", "Māori", "New Zealand Sign Language"], flagEmoji: "🇳🇿" },
  { id: '558', name: "Nicaragua", continent: 'North America', capitals: ["Managua"], languages: ["Spanish"], flagEmoji: "🇳🇮" },
  { id: '562', name: "Niger", continent: 'Africa', capitals: ["Niamey"], languages: ["French"], flagEmoji: "🇳🇪" },
  { id: '566', name: "Nigeria", continent: 'Africa', capitals: ["Abuja"], languages: ["English"], flagEmoji: "🇳🇬" },
  { id: '408', name: "North Korea", continent: 'Asia', capitals: ["Pyongyang"], languages: ["Korean"], flagEmoji: "🇰🇵" },
  { id: '807', name: "North Macedonia", continent: 'Europe', aliases: ["Macedonia"], capitals: ["Skopje"], languages: ["Macedonian"], flagEmoji: "🇲🇰" },
  { id: '578', name: "Norway", continent: 'Europe', capitals: ["Oslo"], languages: ["Norwegian Nynorsk", "Norwegian Bokmål", "Sami"], flagEmoji: "🇳🇴" },
  { id: '512', name: "Oman", continent: 'Asia', capitals: ["Muscat"], languages: ["Arabic"], flagEmoji: "🇴🇲" },
  { id: '586', name: "Pakistan", continent: 'Asia', capitals: ["Islamabad"], languages: ["English", "Urdu"], flagEmoji: "🇵🇰" },
  { id: '585', name: "Palau", continent: 'Oceania', capitals: ["Ngerulmud"], languages: ["English", "Palauan"], flagEmoji: "🇵🇼" },
  { id: '275', name: "Palestine", continent: 'Asia', capitals: ["Ramallah"], languages: ["Arabic"], flagEmoji: "🇵🇸" },
  { id: '591', name: "Panama", continent: 'North America', capitals: ["Panama City"], languages: ["Spanish"], flagEmoji: "🇵🇦" },
  { id: '598', name: "Papua New Guinea", continent: 'Oceania', capitals: ["Port Moresby"], languages: ["English", "Hiri Motu", "Tok Pisin"], flagEmoji: "🇵🇬" },
  { id: '600', name: "Paraguay", continent: 'South America', capitals: ["Asunción"], languages: ["Guaraní", "Spanish"], flagEmoji: "🇵🇾" },
  { id: '604', name: "Peru", continent: 'South America', capitals: ["Lima"], languages: ["Aymara", "Quechua", "Spanish"], flagEmoji: "🇵🇪" },
  { id: '608', name: "Philippines", continent: 'Asia', capitals: ["Manila"], languages: ["English", "Filipino"], flagEmoji: "🇵🇭" },
  { id: '616', name: "Poland", continent: 'Europe', capitals: ["Warsaw"], languages: ["Polish"], flagEmoji: "🇵🇱" },
  { id: '620', name: "Portugal", continent: 'Europe', capitals: ["Lisbon"], languages: ["Portuguese"], flagEmoji: "🇵🇹" },
  { id: '634', name: "Qatar", continent: 'Asia', capitals: ["Doha"], languages: ["Arabic"], flagEmoji: "🇶🇦" },
  { id: '178', name: "Republic of the Congo", continent: 'Africa', aliases: ["Congo", "Congo-Brazzaville"], capitals: ["Brazzaville"], languages: ["French", "Kikongo", "Lingala"], flagEmoji: "🇨🇬" },
  { id: '642', name: "Romania", continent: 'Europe', capitals: ["Bucharest"], languages: ["Romanian"], flagEmoji: "🇷🇴" },
  { id: '643', name: "Russia", continent: 'Europe', aliases: ["Russian Federation"], capitals: ["Moscow"], languages: ["Russian"], flagEmoji: "🇷🇺" },
  { id: '646', name: "Rwanda", continent: 'Africa', capitals: ["Kigali"], languages: ["English", "French", "Kinyarwanda"], flagEmoji: "🇷🇼" },
  { id: '662', name: "Saint Lucia", continent: 'North America', aliases: ["St. Lucia"], capitals: ["Castries"], languages: ["English"], flagEmoji: "🇱🇨" },
  { id: '882', name: "Samoa", continent: 'Oceania', capitals: ["Apia"], languages: ["English", "Samoan"], flagEmoji: "🇼🇸" },
  { id: '674', name: "San Marino", continent: 'Europe', capitals: ["City of San Marino"], languages: ["Italian"], flagEmoji: "🇸🇲" },
  { id: '678', name: "São Tomé and Principe", continent: 'Africa', aliases: ["Sao Tome and Principe"], capitals: ["São Tomé"], languages: ["Portuguese"], flagEmoji: "🇸🇹" },
  { id: '682', name: "Saudi Arabia", continent: 'Asia', capitals: ["Riyadh"], languages: ["Arabic"], flagEmoji: "🇸🇦" },
  { id: '686', name: "Senegal", continent: 'Africa', capitals: ["Dakar"], languages: ["French"], flagEmoji: "🇸🇳" },
  { id: '688', name: "Serbia", continent: 'Europe', capitals: ["Belgrade"], languages: ["Serbian"], flagEmoji: "🇷🇸" },
  { id: '690', name: "Seychelles", continent: 'Africa', capitals: ["Victoria"], languages: ["Seychellois Creole", "English", "French"], flagEmoji: "🇸🇨" },
  { id: '694', name: "Sierra Leone", continent: 'Africa', capitals: ["Freetown"], languages: ["English"], flagEmoji: "🇸🇱" },
  { id: '702', name: "Singapore", continent: 'Asia', capitals: ["Singapore"], languages: ["English", "Malay", "Tamil", "Chinese"], flagEmoji: "🇸🇬" },
  { id: '703', name: "Slovakia", continent: 'Europe', capitals: ["Bratislava"], languages: ["Slovak"], flagEmoji: "🇸🇰" },
  { id: '705', name: "Slovenia", continent: 'Europe', capitals: ["Ljubljana"], languages: ["Slovene"], flagEmoji: "🇸🇮" },
  { id: '090', name: "Solomon Islands", continent: 'Oceania', capitals: ["Honiara"], languages: ["English"], flagEmoji: "🇸🇧" },
  { id: '706', name: "Somalia", continent: 'Africa', capitals: ["Mogadishu"], languages: ["Arabic", "Somali"], flagEmoji: "🇸🇴" },
  { id: '710', name: "South Africa", continent: 'Africa', capitals: ["Pretoria", "Bloemfontein", "Cape Town"], languages: ["Afrikaans", "English", "Southern Ndebele", "Northern Sotho", "Southern Sotho", "Swazi", "Tswana", "Tsonga", "Venda", "Xhosa", "Zulu"], flagEmoji: "🇿🇦" },
  { id: '410', name: "South Korea", continent: 'Asia', capitals: ["Seoul"], languages: ["Korean"], flagEmoji: "🇰🇷" },
  { id: '728', name: "South Sudan", continent: 'Africa', capitals: ["Juba"], languages: ["English"], flagEmoji: "🇸🇸" },
  { id: '724', name: "Spain", continent: 'Europe', capitals: ["Madrid"], languages: ["Spanish"], flagEmoji: "🇪🇸" },
  { id: '144', name: "Sri Lanka", continent: 'Asia', capitals: ["Colombo"], languages: ["Sinhala", "Tamil"], flagEmoji: "🇱🇰" },
  { id: '659', name: "St. Kitts and Nevis", continent: 'North America', capitals: ["Basseterre"], languages: ["English"], flagEmoji: "🇰🇳" },
  { id: '670', name: "St. Vincent and the Grenadines", continent: 'North America', aliases: ["Saint Vincent and the Grenadines"], capitals: ["Kingstown"], languages: ["English"], flagEmoji: "🇻🇨" },
  { id: '729', name: "Sudan", continent: 'Africa', capitals: ["Khartoum"], languages: ["Arabic", "English"], flagEmoji: "🇸🇩" },
  { id: '740', name: "Suriname", continent: 'South America', capitals: ["Paramaribo"], languages: ["Dutch"], flagEmoji: "🇸🇷" },
  { id: '752', name: "Sweden", continent: 'Europe', capitals: ["Stockholm"], languages: ["Swedish"], flagEmoji: "🇸🇪" },
  { id: '756', name: "Switzerland", continent: 'Europe', capitals: ["Bern"], languages: ["French", "Swiss German", "Italian", "Romansh"], flagEmoji: "🇨🇭" },
  { id: '760', name: "Syria", continent: 'Asia', capitals: ["Damascus"], languages: ["Arabic"], flagEmoji: "🇸🇾" },
  { id: '158', name: "Taiwan", continent: 'Asia', capitals: ["Taipei"], languages: ["Chinese"], flagEmoji: "🇹🇼" },
  { id: '762', name: "Tajikistan", continent: 'Asia', capitals: ["Dushanbe"], languages: ["Russian", "Tajik"], flagEmoji: "🇹🇯" },
  { id: '834', name: "Tanzania", continent: 'Africa', capitals: ["Dodoma"], languages: ["English", "Swahili"], flagEmoji: "🇹🇿" },
  { id: '764', name: "Thailand", continent: 'Asia', capitals: ["Bangkok"], languages: ["Thai"], flagEmoji: "🇹🇭" },
  { id: '626', name: "Timor-Leste", continent: 'Asia', aliases: ["East Timor"], capitals: ["Dili"], languages: ["Portuguese", "Tetum"], flagEmoji: "🇹🇱" },
  { id: '768', name: "Togo", continent: 'Africa', capitals: ["Lomé"], languages: ["French"], flagEmoji: "🇹🇬" },
  { id: '776', name: "Tonga", continent: 'Oceania', capitals: ["Nuku'alofa"], languages: ["English", "Tongan"], flagEmoji: "🇹🇴" },
  { id: '780', name: "Trinidad and Tobago", continent: 'North America', capitals: ["Port of Spain"], languages: ["English"], flagEmoji: "🇹🇹" },
  { id: '788', name: "Tunisia", continent: 'Africa', capitals: ["Tunis"], languages: ["Arabic"], flagEmoji: "🇹🇳" },
  { id: '792', name: "Turkey", continent: 'Asia', aliases: ["Turkiye", "Türkiye"], capitals: ["Ankara"], languages: ["Turkish"], flagEmoji: "🇹🇷" },
  { id: '795', name: "Turkmenistan", continent: 'Asia', capitals: ["Ashgabat"], languages: ["Russian", "Turkmen"], flagEmoji: "🇹🇲" },
  { id: '798', name: "Tuvalu", continent: 'Oceania', capitals: ["Funafuti"], languages: ["English", "Tuvaluan"], flagEmoji: "🇹🇻" },
  { id: '800', name: "Uganda", continent: 'Africa', capitals: ["Kampala"], languages: ["English", "Swahili"], flagEmoji: "🇺🇬" },
  { id: '804', name: "Ukraine", continent: 'Europe', capitals: ["Kyiv"], languages: ["Ukrainian"], flagEmoji: "🇺🇦" },
  { id: '784', name: "United Arab Emirates", continent: 'Asia', aliases: ["UAE"], capitals: ["Abu Dhabi"], languages: ["Arabic"], flagEmoji: "🇦🇪" },
  { id: '826', name: "United Kingdom", continent: 'Europe', aliases: ["UK", "Great Britain", "Britain"], capitals: ["London"], languages: ["English"], flagEmoji: "🇬🇧" },
  { id: '840', name: "United States of America", continent: 'North America', aliases: ["United States", "USA", "US", "America"], capitals: ["Washington D.C."], languages: ["English"], flagEmoji: "🇺🇸" },
  { id: '858', name: "Uruguay", continent: 'South America', capitals: ["Montevideo"], languages: ["Spanish"], flagEmoji: "🇺🇾" },
  { id: '860', name: "Uzbekistan", continent: 'Asia', capitals: ["Tashkent"], languages: ["Russian", "Uzbek"], flagEmoji: "🇺🇿" },
  { id: '548', name: "Vanuatu", continent: 'Oceania', capitals: ["Port Vila"], languages: ["Bislama", "English", "French"], flagEmoji: "🇻🇺" },
  { id: '336', name: "Vatican City", continent: 'Europe', aliases: ["Vatican", "Holy See"], capitals: ["Vatican City"], languages: ["Italian", "Latin"], flagEmoji: "🇻🇦" },
  { id: '862', name: "Venezuela", continent: 'South America', capitals: ["Caracas"], languages: ["Spanish"], flagEmoji: "🇻🇪" },
  { id: '704', name: "Vietnam", continent: 'Asia', capitals: ["Hanoi"], languages: ["Vietnamese"], flagEmoji: "🇻🇳" },
  { id: '887', name: "Yemen", continent: 'Asia', capitals: ["Sana'a"], languages: ["Arabic"], flagEmoji: "🇾🇪" },
  { id: '894', name: "Zambia", continent: 'Africa', capitals: ["Lusaka"], languages: ["English"], flagEmoji: "🇿🇲" },
  { id: '716', name: "Zimbabwe", continent: 'Africa', capitals: ["Harare"], languages: ["Chibarwe", "English", "Kalanga", "Khoisan", "Ndau", "Northern Ndebele", "Chewa", "Shona", "Sotho", "Tonga", "Tswana", "Tsonga", "Venda", "Xhosa", "Zimbabwean Sign Language"], flagEmoji: "🇿🇼" },
];

export const COUNTRY_BY_ID: Record<string, CountryDef> = Object.fromEntries(COUNTRIES.map((c) => [c.id, c]));
